name: Changelog CI

on:
  workflow_dispatch:
permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2