name: "Deploy"

on:
  workflow_run:
    workflows: ["Generate changelog"] # 当前工作流的名称
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 添加你的部署步骤
      - name: Deploy
        run: echo "Deploying..111."