# 部署工作流的 YAML 文件（例如 .github/workflows/deploy.yml）
name: "Deploy"

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }} # 从 API 调用中获取分支名称

      # 添加你的部署步骤
      - name: Deploy
        run: echo "Deploying on branch ${{ github.event.client_payload.ref }}..."